main: de.unknown.main.main
name: Project_Lobby
author: Unknown
version: 0.0.6

commands:
     spawn:
          description: Shows MySQL Information
          usage: </command>
     install:
          description: Shows MySQL Information
          usage: </command>
     gm:
          description: Shows MySQL Information
          usage: </command>
          aliases: [gamemode]
     settings:
          description: Shows MySQL Information
          usage: </command>            