main: de.unknown.main.main
name: Project_Lobby
author: Unknown
version: 0.0.3

commands:
     spawn:
          description: Shows MySQL Information
          usage: </command>
     install:
          description: Shows MySQL Information
          usage: </command>       